runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2

#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
- ^(.*/)?venv/.*$
#[END_EXCLUDE]

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: main.api

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

# [START env_vars]
env_variables:
  ENDPOINTS_SERVICE_NAME: acme-api.[project-id-without-brackets].appspot.com
  ENDPOINTS_SERVICE_VERSION: 2017-11-21r0
 # [END env_vars]
